version: "3"
services:
    app:
        build: .
        ports:
            - "8080:8080"
        container_name: flask_test
        env_file:
            - .env
        volumes:
            - ./:/app

    elasticsearch:
        image: "elasticsearch:7.5.1"
        ports:
            - "9200:9200"
        volumes:
            - ./:/app
        tty: true
        environment:
            discovery.type: single-node